apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-php-deployment
  namespace: cloudbees-core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: my-php-app
        image: ananthkannan/mypython-app-may20:$BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
